import { ChannelType, type TextChannel, type Message } from 'discord.js';
import type { Ticket } from '../../database/repositories/ticketsRepo.js';

export interface TranscriptMessage {
  authorTag: string;
  authorId: string;
  authorBot: boolean;
  timestampIso: string;
  content: string;
  attachments: { name: string; url: string }[];
  embedCount: number;
}

export interface TranscriptMeta {
  ticketNumber: number;
  category: string;
  subject: string | null;
  openerId: string;
  guildName: string;
  createdAt: string;
  closedAt?: string | null;
  closedBy?: string | null;
}

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * PURE transcript renderer (unit-tested). Turns ticket metadata + a list of
 * message records into a clean, self-contained HTML document. Only ever
 * receives messages from the ticket channel — no unrelated channels.
 */
export function renderTranscriptHtml(
  meta: TranscriptMeta,
  messages: TranscriptMessage[],
): string {
  const rows = messages
    .map((m) => {
      const time = esc(m.timestampIso);
      const badge = m.authorBot ? ' <span class="bot">BOT</span>' : '';
      const body = m.content ? `<div class="content">${esc(m.content)}</div>` : '';
      const files = m.attachments.length
        ? `<div class="attachments">${m.attachments
            .map((a) => `📎 <a href="${esc(a.url)}" rel="noopener noreferrer">${esc(a.name)}</a>`)
            .join('<br>')}</div>`
        : '';
      const embeds = m.embedCount
        ? `<div class="embeds">📋 ${m.embedCount} embed(s)</div>`
        : '';
      return `
        <div class="msg">
          <div class="meta"><span class="author">${esc(m.authorTag)}</span>${badge}
            <span class="ts">${time}</span></div>
          ${body}${files}${embeds}
        </div>`;
    })
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>LGCY Ticket #${meta.ticketNumber} — Transcript</title>
<style>
  :root { --blue:#2b8cff; --accent:#4fd2ff; --bg:#0d1424; --panel:#161f36; --text:#e7eefc; --muted:#8ea3c8; }
  * { box-sizing: border-box; }
  body { margin:0; background:var(--bg); color:var(--text); font-family:'Segoe UI',system-ui,Arial,sans-serif; }
  .wrap { max-width: 880px; margin: 0 auto; padding: 24px; }
  header { background:linear-gradient(135deg,#123a8a,#2b8cff); border-radius:16px; padding:20px 24px; box-shadow:0 0 30px rgba(79,210,255,.25); }
  header h1 { margin:0 0 6px; font-size:24px; }
  header .tag { color:#dbe9ff; font-size:14px; }
  .metaGrid { display:grid; grid-template-columns:repeat(2,1fr); gap:8px 24px; margin-top:14px; font-size:14px; }
  .metaGrid b { color:var(--accent); }
  .log { margin-top:20px; }
  .msg { background:var(--panel); border-left:3px solid var(--blue); border-radius:10px; padding:10px 14px; margin:10px 0; }
  .msg .meta { font-size:13px; color:var(--muted); margin-bottom:4px; }
  .msg .author { color:var(--text); font-weight:600; }
  .msg .ts { margin-left:8px; }
  .bot { background:var(--blue); color:#fff; font-size:10px; padding:1px 5px; border-radius:4px; margin-left:6px; }
  .content { white-space:pre-wrap; word-wrap:break-word; }
  .attachments,.embeds { margin-top:6px; font-size:13px; color:var(--muted); }
  a { color:var(--accent); }
  footer { text-align:center; color:var(--muted); font-size:12px; margin:24px 0; }
</style></head>
<body><div class="wrap">
  <header>
    <h1>🎫 LGCY Ticket #${meta.ticketNumber}</h1>
    <div class="tag">${esc(meta.guildName)}</div>
    <div class="metaGrid">
      <div><b>Category:</b> ${esc(meta.category)}</div>
      <div><b>Subject:</b> ${esc(meta.subject ?? '—')}</div>
      <div><b>Opened by:</b> ${esc(meta.openerId)}</div>
      <div><b>Created:</b> ${esc(meta.createdAt)}</div>
      ${meta.closedAt ? `<div><b>Closed:</b> ${esc(meta.closedAt)}</div>` : ''}
      ${meta.closedBy ? `<div><b>Closed by:</b> ${esc(meta.closedBy)}</div>` : ''}
      <div><b>Messages:</b> ${messages.length}</div>
    </div>
  </header>
  <div class="log">
    ${rows || '<p class="tag">No messages were sent in this ticket.</p>'}
  </div>
  <footer>Generated by LGCY Core · ${esc(new Date().toISOString())}</footer>
</div></body></html>`;
}

/** Fetches up to `limit` messages (oldest→newest) from a ticket channel. */
async function collectMessages(channel: TextChannel, limit = 1000): Promise<TranscriptMessage[]> {
  const collected: Message[] = [];
  let before: string | undefined;
  while (collected.length < limit) {
    const batch = await channel.messages.fetch({ limit: 100, before });
    if (batch.size === 0) break;
    collected.push(...batch.values());
    before = batch.last()?.id;
    if (batch.size < 100) break;
  }
  return collected
    .sort((a, b) => a.createdTimestamp - b.createdTimestamp)
    .map((m) => ({
      authorTag: m.author?.tag ?? 'Unknown',
      authorId: m.author?.id ?? '0',
      authorBot: m.author?.bot ?? false,
      timestampIso: new Date(m.createdTimestamp).toISOString(),
      content: m.content ?? '',
      attachments: [...m.attachments.values()].map((a) => ({ name: a.name ?? 'file', url: a.url })),
      embedCount: m.embeds.length,
    }));
}

export interface GeneratedTranscript {
  html: string;
  buffer: Buffer;
  filename: string;
  messageCount: number;
}

/** Produces an HTML transcript for a ticket channel. */
export async function generateTranscript(
  channel: TextChannel,
  ticket: Ticket,
): Promise<GeneratedTranscript> {
  if (channel.type !== ChannelType.GuildText) {
    throw new Error('Transcripts can only be generated for text channels.');
  }
  const messages = await collectMessages(channel);
  const html = renderTranscriptHtml(
    {
      ticketNumber: ticket.ticketNumber,
      category: ticket.category,
      subject: ticket.subject,
      openerId: ticket.openerId,
      guildName: channel.guild.name,
      createdAt: ticket.createdAt,
      closedAt: ticket.closedAt,
      closedBy: ticket.closedBy,
    },
    messages,
  );
  return {
    html,
    buffer: Buffer.from(html, 'utf8'),
    filename: `ticket-${ticket.ticketNumber}-transcript.html`,
    messageCount: messages.length,
  };
}
